package com.example.apppetra2.DAO;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import com.example.apppetra2.Classes.Uc06;
import com.example.apppetra2.Conexao.Conexao;

public class Uc06DAOSync {
    private SQLiteDatabase banco;
    private Conexao conexao;

    public Uc06DAOSync(Context context){
        conexao= new Conexao(context);
        banco=conexao.getWritableDatabase();
    }
    public long inserir(Uc06 uc06){
        ContentValues values=new ContentValues();
        values.put("motorista",uc06.getMotorista());
        values.put("data",uc06.getData());
        values.put("horaInicial",uc06.getHoraInicial());
        values.put("horaFinal", uc06.getHoraFinal());
        values.put("horimetroInicial",uc06.getHorimetroInicial());
        values.put("horimetroFinal",uc06.getHorimetroFinal());
        values.put("paradaInicial1",uc06.getParadaInicial1());
        values.put("paradaFinal1",uc06.getParadaFinal1());
        values.put("descricao1",uc06.getDescricao1());
        values.put("paradaInicial2",uc06.getParadaInicial2());
        values.put("paradaFinal2",uc06.getParadaFinal2());
        values.put("descricao2",uc06.getDescricao2());
        values.put("paradaInicial3",uc06.getParadaInicial3());
        values.put("paradaFinal3",uc06.getParadaFinal3());
        values.put("descricao3",uc06.getDescricao3());
        values.put("paradaInicial4",uc06.getParadaInicial4());
        values.put("paradaFinal4",uc06.getParadaFinal4());
        values.put("descricao4",uc06.getDescricao4());
        values.put("paradaInicial5",uc06.getParadaInicial5());
        values.put("paradaFinal5",uc06.getParadaFinal5());
        values.put("descricao5",uc06.getDescricao5());
        values.put("paradaInicial6",uc06.getParadaInicial6());
        values.put("paradaFinal6",uc06.getParadaFinal6());
        values.put("descricao6",uc06.getDescricao6());
        values.put("paradaInicial7",uc06.getParadaInicial7());
        values.put("paradaFinal7",uc06.getParadaFinal7());
        values.put("descricao7",uc06.getDescricao7());
        values.put("paradaInicial8",uc06.getParadaInicial8());
        values.put("paradaFinal8",uc06.getParadaFinal8());
        values.put("descricao8",uc06.getDescricao8());
        values.put("paradaInicial9",uc06.getParadaInicial9());
        values.put("paradaFinal9",uc06.getParadaFinal9());
        values.put("descricao9",uc06.getDescricao9());
        values.put("paradaInicial10",uc06.getParadaInicial10());
        values.put("paradaFinal10",uc06.getParadaFinal10());
        values.put("descricao10",uc06.getDescricao10());
        values.put("b0Volume",uc06.getB0Vol());
        values.put("b0NumeroDeViagens",uc06.getB0NumViagens());
        values.put("b0Motorista",uc06.getB0Mot());
        values.put("b1Volume",uc06.getB1Vol());
        values.put("b1NumeroDeViagens",uc06.getB1NumViagens());
        values.put("b1Motorista",uc06.getB1Mot());
        values.put("b2Volume",uc06.getB2Vol());
        values.put("b2NumeroDeViagens",uc06.getB2NumViagens());
        values.put("b2Motorista",uc06.getB2Mot());
        values.put("b4Volume",uc06.getB4Vol());
        values.put("b4NumeroDeViagens",uc06.getB4NumViagens());
        values.put("b4Motorista",uc06.getB4Mot());
        values.put("aimVolume",uc06.getAimVol());
        values.put("aimNumeroDeViagens",uc06.getAimNumViagens());
        values.put("aimMotorista",uc06.getAimMot());
        values.put("aifVolume",uc06.getAifVol());
        values.put("aifNumeroDeViagens",uc06.getAifNumViagens());
        values.put("aifMotorista",uc06.getAifMot());
        values.put("bicaVolume",uc06.getBicaVol());
        values.put("bicaNumeroDeViagens",uc06.getBicaNumViagens());
        values.put("bicaMotorista",uc06.getBicaMot());
        values.put("areiaMediaPracaToco",uc06.getAmprToco());
        values.put("areiaMediaPracaTruck",uc06.getAmprTruck());
        values.put("areiaMediaPracaCarreta",uc06.getAmprCarreta());
        values.put("areiaMediaPracaAxor",uc06.getAmprAxor());
        values.put("areiaMediaPracaObs",uc06.getAmprObs());
        values.put("areiaMediaUmToco",uc06.getAmumToco());
        values.put("areiaMediaUmTruck",uc06.getAmumTruck());
        values.put("areiaMediaUmCarreta",uc06.getAmumCarreta());
        values.put("areiaMediaUmAxor",uc06.getAmumAxor());
        values.put("areiaMediaUmObs",uc06.getAmumObs());
        values.put("areiaFinaToco",uc06.getAfToco());
        values.put("areiaFinaTruck",uc06.getAfTruck());
        values.put("areiaFinaCarreta",uc06.getAfCarreta());
        values.put("areiaFinaAxor",uc06.getAfAxor());
        values.put("areiaFinaObs",uc06.getAfObs());
        values.put("pedriscoToco",uc06.getPedToco());
        values.put("pedriscoTruck",uc06.getPedTruck());
        values.put("pedriscoCarreta",uc06.getPedCarreta());
        values.put("pedriscoAxor",uc06.getPedAxor());
        values.put("pedriscoObs",uc06.getPedObs());
        values.put("bicaPracaToco",uc06.getBicaPrToco());
        values.put("bicaPracaTruck",uc06.getBicaPrTruck());
        values.put("bicaPracaCarreta",uc06.getBicaPrCarreta());
        values.put("bicaPracaAxor",uc06.getBicaPrAxor());
        values.put("bicaPracaObs",uc06.getBicaPrObs());
        values.put("bica790Toco",uc06.getBica790Toco());
        values.put("bica790Truck",uc06.getBica790Truck());
        values.put("bica790Carreta",uc06.getBica790Carreta());
        values.put("bica790Axor",uc06.getBica790Axor());
        values.put("bica790Obs",uc06.getBica790Obs());
        values.put("bicaUmToco",uc06.getBicaUmToco());
        values.put("bicaUmTruck",uc06.getBicaUmTruck());
        values.put("bicaUmCarreta",uc06.getBicaUmCarreta());
        values.put("bicaUmAxor",uc06.getBicaUmAxor());
        values.put("bicaUmObs",uc06.getBicaUmObs());
        values.put("brita1PracaToco",uc06.getBr1PrToco());
        values.put("brita1PracaTruck",uc06.getBr1PrTruck());
        values.put("brita1PracaCarreta",uc06.getBr1PrCarreta());
        values.put("brita1PracaAxor",uc06.getBr1PrAxor());
        values.put("brita1PracaObs",uc06.getBr1PrObs());
        values.put("brita119Toco",uc06.getBr119Toco());
        values.put("brita119Truck",uc06.getBr119Truck());
        values.put("brita119Carreta",uc06.getBr119Carreta());
        values.put("brita119Axor",uc06.getBr119Axor());
        values.put("brita119Obs",uc06.getBr119Obs());
        values.put("brita0pracaToco",uc06.getBr0PrToco());
        values.put("brita0pracaTruck",uc06.getBr0PrTruck());
        values.put("brita0pracaCarreta",uc06.getBr0PrCarreta());
        values.put("brita0pracaAxor",uc06.getBr0PrAxor());
        values.put("brita0pracaObs",uc06.getBr0PrObs());
        values.put("brita0UmToco",uc06.getBr0UmToco());
        values.put("brita0UmTruck",uc06.getBr0UmTruck());
        values.put("brita0UmCarreta",uc06.getBr0UmCarreta());
        values.put("brita0UmAxor",uc06.getBr0UmAxor());
        values.put("brita0UmObs",uc06.getBr0UmObs());
        values.put("somaToco",uc06.getSomaToco());
        values.put("somaTruck",uc06.getSomaTruck());
        values.put("somaCarreta",uc06.getSomaCarreta());
        values.put("somaAxor",uc06.getSomaAxor());
        values.put("lanternagem",uc06.getLanternagem());
        values.put("pneus",uc06.getPneus());
        values.put("h2o",uc06.getH2o());
        values.put("oleo",uc06.getOleo());
        values.put("direcao",uc06.getDirecao());
        values.put("freios",uc06.getFreios());
        values.put("parteEletrica",uc06.getParteEletrica());
        values.put("observacoes",uc06.getObservacoes());
        return banco.insert("uc06",null, values);    }


}
