package com.example.apppetra2.DAO;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import com.example.apppetra2.Classes.Uc07;
import com.example.apppetra2.Conexao.Conexao;

public class Uc07DAOSync {
    private SQLiteDatabase banco;
    private Conexao conexao;

    public Uc07DAOSync(Context context){
        conexao= new Conexao(context);
        banco=conexao.getWritableDatabase();
    }
    public long inserir(Uc07 uc07){
        ContentValues values=new ContentValues();
        values.put("motorista",uc07.getMotorista());
        values.put("data",uc07.getData());
        values.put("horaInicial",uc07.getHoraInicial());
        values.put("horaFinal", uc07.getHoraFinal());
        values.put("horimetroInicial",uc07.getHorimetroInicial());
        values.put("horimetroFinal",uc07.getHorimetroFinal());
        values.put("paradaInicial1",uc07.getParadaInicial1());
        values.put("paradaFinal1",uc07.getParadaFinal1());
        values.put("descricao1",uc07.getDescricao1());
        values.put("paradaInicial2",uc07.getParadaInicial2());
        values.put("paradaFinal2",uc07.getParadaFinal2());
        values.put("descricao2",uc07.getDescricao2());
        values.put("paradaInicial3",uc07.getParadaInicial3());
        values.put("paradaFinal3",uc07.getParadaFinal3());
        values.put("descricao3",uc07.getDescricao3());
        values.put("paradaInicial4",uc07.getParadaInicial4());
        values.put("paradaFinal4",uc07.getParadaFinal4());
        values.put("descricao4",uc07.getDescricao4());
        values.put("paradaInicial5",uc07.getParadaInicial5());
        values.put("paradaFinal5",uc07.getParadaFinal5());
        values.put("descricao5",uc07.getDescricao5());
        values.put("paradaInicial6",uc07.getParadaInicial6());
        values.put("paradaFinal6",uc07.getParadaFinal6());
        values.put("descricao6",uc07.getDescricao6());
        values.put("paradaInicial7",uc07.getParadaInicial7());
        values.put("paradaFinal7",uc07.getParadaFinal7());
        values.put("descricao7",uc07.getDescricao7());
        values.put("paradaInicial8",uc07.getParadaInicial8());
        values.put("paradaFinal8",uc07.getParadaFinal8());
        values.put("descricao8",uc07.getDescricao8());
        values.put("paradaInicial9",uc07.getParadaInicial9());
        values.put("paradaFinal9",uc07.getParadaFinal9());
        values.put("descricao9",uc07.getDescricao9());
        values.put("paradaInicial10",uc07.getParadaInicial10());
        values.put("paradaFinal10",uc07.getParadaFinal10());
        values.put("descricao10",uc07.getDescricao10());
        values.put("b0Volume",uc07.getB0Vol());
        values.put("b0NumeroDeViagens",uc07.getB0NumViagens());
        values.put("b0Motorista",uc07.getB0Mot());
        values.put("b1Volume",uc07.getB1Vol());
        values.put("b1NumeroDeViagens",uc07.getB1NumViagens());
        values.put("b1Motorista",uc07.getB1Mot());
        values.put("b2Volume",uc07.getB2Vol());
        values.put("b2NumeroDeViagens",uc07.getB2NumViagens());
        values.put("b2Motorista",uc07.getB2Mot());
        values.put("b4Volume",uc07.getB4Vol());
        values.put("b4NumeroDeViagens",uc07.getB4NumViagens());
        values.put("b4Motorista",uc07.getB4Mot());
        values.put("aimVolume",uc07.getAimVol());
        values.put("aimNumeroDeViagens",uc07.getAimNumViagens());
        values.put("aimMotorista",uc07.getAimMot());
        values.put("aifVolume",uc07.getAifVol());
        values.put("aifNumeroDeViagens",uc07.getAifNumViagens());
        values.put("aifMotorista",uc07.getAifMot());
        values.put("bicaVolume",uc07.getBicaVol());
        values.put("bicaNumeroDeViagens",uc07.getBicaNumViagens());
        values.put("bicaMotorista",uc07.getBicaMot());
        values.put("areiaMediaPracaToco",uc07.getAmprToco());
        values.put("areiaMediaPracaTruck",uc07.getAmprTruck());
        values.put("areiaMediaPracaCarreta",uc07.getAmprCarreta());
        values.put("areiaMediaPracaAxor",uc07.getAmprAxor());
        values.put("areiaMediaPracaObs",uc07.getAmprObs());
        values.put("areiaMediaUmToco",uc07.getAmumToco());
        values.put("areiaMediaUmTruck",uc07.getAmumTruck());
        values.put("areiaMediaUmCarreta",uc07.getAmumCarreta());
        values.put("areiaMediaUmAxor",uc07.getAmumAxor());
        values.put("areiaMediaUmObs",uc07.getAmumObs());
        values.put("areiaFinaToco",uc07.getAfToco());
        values.put("areiaFinaTruck",uc07.getAfTruck());
        values.put("areiaFinaCarreta",uc07.getAfCarreta());
        values.put("areiaFinaAxor",uc07.getAfAxor());
        values.put("areiaFinaObs",uc07.getAfObs());
        values.put("pedriscoToco",uc07.getPedToco());
        values.put("pedriscoTruck",uc07.getPedTruck());
        values.put("pedriscoCarreta",uc07.getPedCarreta());
        values.put("pedriscoAxor",uc07.getPedAxor());
        values.put("pedriscoObs",uc07.getPedObs());
        values.put("bicaPracaToco",uc07.getBicaPrToco());
        values.put("bicaPracaTruck",uc07.getBicaPrTruck());
        values.put("bicaPracaCarreta",uc07.getBicaPrCarreta());
        values.put("bicaPracaAxor",uc07.getBicaPrAxor());
        values.put("bicaPracaObs",uc07.getBicaPrObs());
        values.put("bica790Toco",uc07.getBica790Toco());
        values.put("bica790Truck",uc07.getBica790Truck());
        values.put("bica790Carreta",uc07.getBica790Carreta());
        values.put("bica790Axor",uc07.getBica790Axor());
        values.put("bica790Obs",uc07.getBica790Obs());
        values.put("bicaUmToco",uc07.getBicaUmToco());
        values.put("bicaUmTruck",uc07.getBicaUmTruck());
        values.put("bicaUmCarreta",uc07.getBicaUmCarreta());
        values.put("bicaUmAxor",uc07.getBicaUmAxor());
        values.put("bicaUmObs",uc07.getBicaUmObs());
        values.put("brita1PracaToco",uc07.getBr1PrToco());
        values.put("brita1PracaTruck",uc07.getBr1PrTruck());
        values.put("brita1PracaCarreta",uc07.getBr1PrCarreta());
        values.put("brita1PracaAxor",uc07.getBr1PrAxor());
        values.put("brita1PracaObs",uc07.getBr1PrObs());
        values.put("brita119Toco",uc07.getBr119Toco());
        values.put("brita119Truck",uc07.getBr119Truck());
        values.put("brita119Carreta",uc07.getBr119Carreta());
        values.put("brita119Axor",uc07.getBr119Axor());
        values.put("brita119Obs",uc07.getBr119Obs());
        values.put("brita0pracaToco",uc07.getBr0PrToco());
        values.put("brita0pracaTruck",uc07.getBr0PrTruck());
        values.put("brita0pracaCarreta",uc07.getBr0PrCarreta());
        values.put("brita0pracaAxor",uc07.getBr0PrAxor());
        values.put("brita0pracaObs",uc07.getBr0PrObs());
        values.put("brita0UmToco",uc07.getBr0UmToco());
        values.put("brita0UmTruck",uc07.getBr0UmTruck());
        values.put("brita0UmCarreta",uc07.getBr0UmCarreta());
        values.put("brita0UmAxor",uc07.getBr0UmAxor());
        values.put("brita0UmObs",uc07.getBr0UmObs());
        values.put("somaToco",uc07.getSomaToco());
        values.put("somaTruck",uc07.getSomaTruck());
        values.put("somaCarreta",uc07.getSomaCarreta());
        values.put("somaAxor",uc07.getSomaAxor());
        values.put("lanternagem",uc07.getLanternagem());
        values.put("pneus",uc07.getPneus());
        values.put("h2o",uc07.getH2o());
        values.put("oleo",uc07.getOleo());
        values.put("direcao",uc07.getDirecao());
        values.put("freios",uc07.getFreios());
        values.put("parteEletrica",uc07.getParteEletrica());
        values.put("observacoes",uc07.getObservacoes());
        return banco.insert("uc07",null, values);    }


}
